labels: ["new feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in a new feature for StreamSharp! Please ensure you're in the right repo for the feature you want.

        If this is for a feature that requires an entirely new helper method, please go to StreamSharp.Base and post your helper method request in said discussion category.
  - type: input
    attributes:
      label: Brief overview
      description: In one or two sentences, what does the enhancement set out to achieve?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Relation to problem?
      description: Does your enhancement request relate to a problem?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Give more details
      description: If you selected yes to it being related to a problem, please give us more details. If this isn't related to a problem please type 'N/A'
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Please give details of any alternative solutions you have considered
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are trying to resolve!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct & Contributing
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it. The Contributing Guidelines help ensure a consistent code structure.
      options:
        - label: I agree to follow this project's Code of Conduct (link is in the helpful resources section)
          required: true
        - label: I agree to follow this project's Contributing Guidelines (link is in the helpful resources section)
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request form, and for your interest in improving our products!