name: Bug Report
description: If something isn't working as it should, please file a report here. If you have a feature request or vulnerability report, clicking the template will give you information on how to approach this.
title: "[BUG]: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        In order to simplify the process of gathering issues, we have a standardised form for you to fill out.

        If you are reporting a **security vulnerability** please visit the security advisories for the selected repo
        If you have a **feature request** please visit the ideas category in the discussions page of the repo in question.
        If your suggestion is for a **new helper module** please visit the StreamSharp.Base repo and post the suggestion in the *Helper Module Requests* category.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues and found potentially similar issues
      - label: I have searched the existing issues and found nothing remotely like this issue
    validations:
      required: true
  - type: input
    attributes:
      label: Similar issues
      description: If you found any potentially similar issues, please link them
    validations:
      required: false
  - type: input
    attributes:
      label: Overview
      description: A brief description of the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS
      description: Please tell us which OS you're using
      options:
        - Windows
        - Mac
        - Linux
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS Ver**: 20.04
          - **IDE**: Visual Studio Community 2022
          - **SS Ver**: 1.0.0.0
      value: |
          - OS Ver:
          - IDE:
          - SS Ver:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
