name: Bug Report
description: If something isn't working as it should, please file a report here. If you have a vulnerability report, clicking the template will give you information on how to approach this.
title: "[BUG]: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        In order to simplify the process of gathering bug reports, we have a standardised form for you to fill out.

        If you are reporting a **security vulnerability** please visit the security advisories for the selected repo
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues and found potentially similar issues
      - label: I have searched the existing issues and found nothing remotely like this issue
    validations:
      required: true
  - type: input
    attributes:
      label: Similar issues
      description: If you found any potentially similar issues, please link them. Otherwise, please type 'N/A'
    validations:
      required: true
  - type: input
    attributes:
      label: Overview
      description: A brief description of the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      render: markdown
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS
      description: Please tell us which OS you're using while developing plugins with StreamSharp
      options:
        - Windows
        - Mac
        - Linux
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please tell us the environment you're using when facing this issue. Include the versions of any helper modules you're using

        Please use the format **OS Ver**: [version info] - see the placeholder for more info. Each item should go on a separate line.
      placeholder: |
        - **OS Ver**: 20.04
        - **IDE**: Visual Studio Community 2022
        - **StreamSharp Ver**: 1.0.0.0)
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct & Contributing
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it. The Contributing Guidelines help ensure a consistent code structure.
      options:
        - label: I agree to follow this project's Code of Conduct (link is in the helpful resources section)
          required: true
        - label: I agree to follow this project's Contributing Guidelines (link is in the helpful resources section)
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report, and for your interest in improving our products!
