blank_issues_enabled: false
contact_links:
  - name: "Bug Report"
    url: "/ISSUE_TEMPLATE/bug_report.md"
    about: "Report a bug to help improve the project"
  - name: "Feature Request"
    url: "/ISSUE_TEMPLATE/feature_request.md"
    about: "Suggest a new feature or enhancement"
